In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

In [2]:
img_yes = '../data/yes/'
img_no = '../data/no/'

yes_files = os.listdir(img_yes)
no_files = os.listdir(img_no)

yes_images, no_images = [], []
print('[!] Reading files with positive diagnostic...')
for file in yes_files:
    yes_images.append(plt.imread(f'{img_yes}{file}'))
print('[!] Positive files read!')

print('[!] Reading files with negative diagnostic...')
for file in no_files:
    no_images.append(plt.imread(f'{img_no}{file}'))
print('[!] Negative files read!')

all_images = yes_images + no_images
YES_SIZE, NO_SIZE = len(yes_images), len(no_images)

[!] Reading files with positive diagnostic...
[!] Positive files read!
[!] Reading files with negative diagnostic...
[!] Negative files read!


In [3]:
THRESH = 30
MAX_VALUE = 255

def convert_to_int_matrix(img_list):
    MIN, MAX = 0, 255
    for i, img in enumerate(img_list):
        if img.dtype == np.float32:
            tmp = np.copy(img) * MAX
            img_list[i] = tmp.astype(np.uint8)

def resize_imgs(img_list, height, width):
    for i, img in enumerate(img_list):
        img_list[i] = cv2.resize(img, (height, width))

def imgs_to_grayscale(img_list):
    for i, img in enumerate(img_list):
        if len(img.shape) == 3:
            img_list[i] = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

def gaussian_blur(img_list):
    for i, img in enumerate(img_list):
        img_list[i] = cv2.GaussianBlur(img, (5, 5), 0) 

def threshold_imgs(img_list):
    for i, img in enumerate(img_list):
        _, img_list[i] = cv2.threshold(img, THRESH, MAX_VALUE, cv2.THRESH_BINARY)

def erode_imgs(img_list, iter=1):
    for i, img in enumerate(img_list):
        img_list[i] = cv2.erode(img, None, iterations=iter)

def dilate_imgs(img_list, iter=1):
    for i, img in enumerate(img_list):
        img_list[i] = cv2.dilate(img, None, iterations=iter)

def flatten_contour(contour_list):
    tmp = contour_list[0]
    shape = tmp.shape
    aux = np.zeros(shape=(shape[0], shape[2]), dtype=int)
    for i in range(shape[0]):
        aux[i] = tmp[i].flatten()
    return aux

def find_extreme_points(contour_list):
    col_1 = contour_list[:, 0]
    col_0 = contour_list[:, 1]
    x_left, x_right = np.argmin(col_0), np.argmax(col_0)
    y_top, y_bot = np.argmax(col_1), np.argmin(col_1)
    ret = np.zeros(shape=(4, 2), dtype=int)
    ret[0, :], ret[1, :] = contour_list[x_left], contour_list[x_right]
    ret[2, :], ret[3, :] = contour_list[y_top], contour_list[y_bot]
    return ret  

def get_contour(img_list_morph, img_list, mode):
    extreme_points, i = [], 0
    for img_morph, img in zip(img_list_morph, img_list):
        cont, _ = cv2.findContours(image=img_morph, mode=mode, method=cv2.CHAIN_APPROX_NONE)
        cont_flat = flatten_contour(cont)
        extreme_points.append(find_extreme_points(cont_flat))
        i+= 1
        if i % 50 == 0: print(f'[!] {i} images processed...')
        # print(extreme_points[-1])
        # img_copy = img.copy()
        # print(f'img_shape: {img_copy.shape}')
        # print(f'extreme_point: {extreme_points[-1]}')
        # for i in range(4):
        #     img_copy = cv2.circle(img_copy, extreme_points[-1][i, :], radius=5, color=(0, 255, 0), thickness=-1)
        # cv2.imshow("Image", img_copy)
        # cv2.waitKey()
        # cv2.drawContours(image=img_copy, contours=cont, contourIdx=-1, color=(0, 255, 0), thickness=4, lineType=cv2.LINE_AA)
        # cv2.imshow("Image", img_copy)
        # cv2.waitKey()
    print(f'[!] Total of {i} images processed!')
    return np.array(extreme_points)  

def draw_img(img_list, index):
    if index < len(img_list):
        cv2.imshow("Brain image", img_list[index])
        cv2.waitKey()

In [4]:
INDEX = 0
HEIGHT, WIDTH = 214, 214
convert_to_int_matrix(all_images)
all_images_morph = all_images.copy()
draw_img(all_images, 0)
resize_imgs(all_images, HEIGHT, WIDTH)
resize_imgs(all_images_morph, HEIGHT, WIDTH)
draw_img(all_images_morph, INDEX)
imgs_to_grayscale(all_images_morph)
draw_img(all_images_morph, INDEX)  
threshold_imgs(all_images_morph)
draw_img(all_images_morph, INDEX)
erode_imgs(all_images_morph)
draw_img(all_images_morph, INDEX)
dilate_imgs(all_images_morph)
draw_img(all_images_morph, INDEX)
gaussian_blur(all_images_morph)
draw_img(all_images_morph, INDEX)
extreme_points = get_contour(all_images_morph, all_images, cv2.RETR_EXTERNAL)

[!] 50 images processed...
[!] 100 images processed...
[!] 150 images processed...
[!] 200 images processed...
[!] 250 images processed...
[!] Total of 253 images processed!


In [5]:
def cut_images(extreme_points, img_list):
    new_images = []
    for extreme_point, img in zip(extreme_points, img_list):
        print(extreme_point)
        x_left, x_right = extreme_point[0, 1], extreme_point[1, 1]
        y_top, y_bot = extreme_point[2, 0], extreme_point[3, 0]
        size_h, size_v = x_right - x_left, y_top - y_bot
        print(f'img_shape: {img.shape}')
        print(f'x_left: {x_left} - x_right: {x_right} - y_top: {y_top} - y_bot: {y_bot}')
        # tmp = np.zeros(shape=(size_h, size_v), dtype=np.uint8)
        # tmp = img[x_left:x_right, y_bot:y_top].copy()
        tmp = np.zeros(shape=(size_h, size_v), dtype=np.uint8)
        for i, k in zip(range(x_left, x_right), range(size_h)):
            for j, l in zip(range(y_bot, y_top), range(size_v)):
                tmp[k, l] = img[i, j]
        new_images.append(tmp)
    return new_images

In [6]:
grey_imgs = all_images.copy()
imgs_to_grayscale(grey_imgs)
new_images = cut_images(extreme_points, grey_imgs)

[[ 89   6]
 [ 86 208]
 [204 108]
 [  6 101]]
img_shape: (214, 214)
x_left: 6 - x_right: 208 - y_top: 204 - y_bot: 6
[[  0   0]
 [  0 213]
 [213 213]
 [  0   0]]
img_shape: (214, 214)
x_left: 0 - x_right: 213 - y_top: 213 - y_bot: 0
[[ 92   6]
 [121 213]
 [203 142]
 [ 12 106]]
img_shape: (214, 214)
x_left: 6 - x_right: 213 - y_top: 203 - y_bot: 12
[[ 92  11]
 [ 92 205]
 [196 128]
 [ 18 112]]
img_shape: (214, 214)
x_left: 11 - x_right: 205 - y_top: 196 - y_bot: 18
[[ 77   0]
 [ 91 213]
 [207 137]
 [ 12 115]]
img_shape: (214, 214)
x_left: 0 - x_right: 213 - y_top: 207 - y_bot: 12
[[  2 205]
 [  0 213]
 [  8 211]
 [  0 209]]
img_shape: (214, 214)
x_left: 205 - x_right: 213 - y_top: 8 - y_bot: 0
[[  0 203]
 [  0 210]
 [ 11 209]
 [  0 203]]
img_shape: (214, 214)
x_left: 203 - x_right: 210 - y_top: 11 - y_bot: 0
[[104   4]
 [ 90 209]
 [193 126]
 [ 14 116]]
img_shape: (214, 214)
x_left: 4 - x_right: 209 - y_top: 193 - y_bot: 14
[[112   3]
 [ 92 213]
 [213 132]
 [  0 106]]
img_shape: (214, 214)

In [7]:
def check_images(img_morph_list, img_list):
    correct_yes_images, correct_no_images = [], []
    incorrect_yes_images, incorrect_no_images = [], []
    for img_morph, img, i in zip(img_morph_list, img_list, range(len(img_list))):
        cv2.imshow("Brain", img_morph)
        key = cv2.waitKey()
        if key == 13:
            if i < YES_SIZE:
                correct_yes_images.append(img_morph)
            else:
                correct_no_images.append(img_morph)
        elif key == 8:
            if i < YES_SIZE:
                incorrect_yes_images.append(img)
            else:
                incorrect_no_images.append(img)
    return correct_yes_images, correct_no_images, incorrect_yes_images, incorrect_no_images

In [8]:
correct_yes_images, correct_no_images, incorrect_yes_images, incorrect_no_images = check_images(new_images, grey_imgs)
# correct_yes_images = np.load('./numpy_arrays/correct_yes_images.npy', allow_pickle=True)
# correct_no_images = np.load('./numpy_arrays/correct_no_images.npy', allow_pickle=True)
# incorrect_yes_images = np.load('./numpy_arrays/incorrect_yes_images.npy', allow_pickle=True)
# incorrect_no_images = np.load('./numpy_arrays/incorrect_no_images.npy', allow_pickle=True)

In [ ]:
print(f'[!] {len(correct_yes_images) + len(correct_no_images)} correct images!')
print(f'[!] {len(incorrect_yes_images) + len(incorrect_no_images)} incorrect images!')

[!] 169 correct images!
[!] 83 incorrect images!


In [ ]:
NP_PATH = './numpy_arrays'
np.save(f'{NP_PATH}/correct_yes_images.npy', correct_yes_images, allow_pickle=True)
np.save(f'{NP_PATH}/correct_no_images.npy', correct_no_images, allow_pickle=True)
np.save(f'{NP_PATH}/incorrect_yes_images.npy', incorrect_yes_images, allow_pickle=True)
np.save(f'{NP_PATH}/incorrect_no_images.npy', incorrect_no_images, allow_pickle=True)

c:\Users\kmart\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py:518: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


: 

In [ ]:
THRESH, INDEX = 20, 0
YES_SIZE, NO_SIZE = len(incorrect_yes_images), len(incorrect_no_images)

original_incorrect_images = np.concatenate((incorrect_yes_images, incorrect_no_images))
all_incorrect_images = original_incorrect_images.copy()

threshold_imgs(all_incorrect_images)
draw_img(all_incorrect_images, INDEX)
erode_imgs(all_incorrect_images)
draw_img(all_incorrect_images, INDEX)
dilate_imgs(all_incorrect_images)
draw_img(all_incorrect_images, INDEX)
gaussian_blur(all_incorrect_images)
draw_img(all_incorrect_images, INDEX)

extreme_points = get_contour(all_incorrect_images, original_incorrect_images, cv2.RETR_EXTERNAL)
new_images = cut_images(extreme_points, original_incorrect_images)
res_imgs = check_images(new_images, original_incorrect_images)

print(f'[!] {len(res_imgs[0]) + len(res_imgs[1])} correct images!')
print(f'[!] {len(res_imgs[2]) + len(res_imgs[3])} incorrect images!')
# for img in all_incorrect_images:
#     cv2.imshow("yes", img)
#     cv2.waitKey()


In [ ]:
res_correct_yes = np.concatenate(np.load(f'{NP_PATH}/correct_yes_images.npy'), res_imgs[0])
res_correct_no = np.concatenate(np.load(f'{NP_PATH}/correct_no_images.npy', res_imgs[1]))
print(f'[!] {len(res_correct_yes) + len(res_correct_no)} total correct images!')
np.save(f'{NP_PATH}/def_correct_yes.npy', res_correct_yes)
np.save(f'{NP_PATH}/def_correct_no.npy', res_correct_no)