In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import imutils

In [2]:
img_yes = '../data/yes/'
img_no = '../data/no/'

yes_files = os.listdir(img_yes)
no_files = os.listdir(img_no)

yes_images, no_images = [], []
print('[!] Reading files with positive diagnostic...')
for file in yes_files:
    yes_images.append(plt.imread(f'{img_yes}{file}'))
print('[!] Positive files read!')

print('[!] Reading files with negative diagnostic...')
for file in no_files:
    no_images.append(plt.imread(f'{img_no}{file}'))
print('[!] Negative files read!')

all_images = yes_images + no_images
N_YES, N_NO = len(yes_images), len(no_images)

[!] Reading files with positive diagnostic...
[!] Positive files read!
[!] Reading files with negative diagnostic...
[!] Negative files read!


In [3]:
THRESH = 30
MAX_VALUE = 255

def convert_to_int_matrix(img_list):
    MIN, MAX = 0, 255
    for i, img in enumerate(img_list):
        if img.dtype == np.float32:
            tmp = np.copy(img) * MAX
            img_list[i] = tmp.astype(np.uint8)

def imgs_to_grayscale(img_list):
    for i, img in enumerate(img_list):
        if len(img.shape) == 3:
            img_list[i] = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

def gaussian_blur(img_list):
    for i, img in enumerate(img_list):
        img_list[i] = cv2.GaussianBlur(img, (5, 5), 0) 

def threshold_imgs(img_list):
    for i, img in enumerate(img_list):
        _, img_list[i] = cv2.threshold(img, THRESH, MAX_VALUE, cv2.THRESH_BINARY)

def erode_imgs(img_list):
    for i, img in enumerate(img_list):
        img_list[i] = cv2.erode(img, None, iterations=1)

def dilate_imgs(img_list):
    for i, img in enumerate(img_list):
        img_list[i] = cv2.dilate(img, None, iterations=1)

def flatten_contour(contour_list):
    tmp = contour_list[0]
    shape = tmp.shape
    aux = np.zeros(shape=(shape[0], shape[2]), dtype=int)
    for i in range(shape[0]):
        aux[i] = tmp[i].flatten()
    return aux

def find_extreme_points(contour_list):
    col_1 = contour_list[:, 0]
    col_0 = contour_list[:, 1]
    x_left, x_right = np.argmin(col_0), np.argmax(col_0)
    y_top, y_bot = np.argmax(col_1), np.argmin(col_1)
    ret = np.zeros(shape=(4, 2), dtype=int)
    ret[0, :], ret[1, :] = contour_list[x_left], contour_list[x_right]
    ret[2, :], ret[3, :] = contour_list[y_top], contour_list[y_bot]
    return ret  

def get_contour(img_list_morph, img_list, mode):
    extreme_points, i = [], 0
    for img_morph, img in zip(img_list_morph, img_list):
        cont, _ = cv2.findContours(image=img_morph, mode=mode, method=cv2.CHAIN_APPROX_NONE)
        cont_flat = flatten_contour(cont)
        extreme_points.append(find_extreme_points(cont_flat))
        i+= 1
        if i % 50 == 0: print(f'[!] {i} images processed...')
        # print(extreme_points[-1])
        # img_copy = img.copy()
        # print(f'img_shape: {img_copy.shape}')
        # print(f'extreme_point: {extreme_points[-1]}')
        # for i in range(4):
        #     img_copy = cv2.circle(img_copy, extreme_points[-1][i, :], radius=5, color=(0, 255, 0), thickness=-1)
        # cv2.imshow("Image", img_copy)
        # cv2.waitKey()
        # cv2.drawContours(image=img_copy, contours=cont, contourIdx=-1, color=(0, 255, 0), thickness=4, lineType=cv2.LINE_AA)
        # cv2.imshow("Image", img_copy)
        # cv2.waitKey()
    print(f'[!] Total of {i} images processed!')
    return np.array(extreme_points)  

def draw_img(img_list, index):
    if index < len(img_list):
        cv2.imshow("Brain image", img_list[index])
        cv2.waitKey()

In [4]:
INDEX = 0
convert_to_int_matrix(all_images)
all_images_morph = all_images.copy()
draw_img(all_images, 0)
imgs_to_grayscale(all_images_morph)
draw_img(all_images_morph, INDEX)  
threshold_imgs(all_images_morph)
draw_img(all_images_morph, INDEX)
erode_imgs(all_images_morph)
draw_img(all_images_morph, INDEX)
dilate_imgs(all_images_morph)
draw_img(all_images_morph, INDEX)
gaussian_blur(all_images_morph)
draw_img(all_images_morph, INDEX)  
extreme_points = get_contour(all_images_morph, all_images, cv2.RETR_EXTERNAL)

[!] 50 images processed...
[!] 100 images processed...
[!] 150 images processed...
[!] 200 images processed...
[!] 250 images processed...
[!] Total of 253 images processed!


In [7]:
def cut_images(extreme_points, img_list):
    new_images = []
    for extreme_point, img in zip(extreme_points, img_list):
        print(extreme_point)
        x_left, x_right = extreme_point[0, 1], extreme_point[1, 1]
        y_top, y_bot = extreme_point[2, 0], extreme_point[3, 0]
        print(f'img_shape: {img.shape}')
        print(f'x_left: {x_left} --- x_right: {x_right} --- y_bot: {y_bot} --- y_top: {y_top}')
        size_h, size_v = x_right - x_left, y_top - y_bot
        tmp = np.zeros(shape=(size_h, size_v), dtype=np.uint8)
        for i, k in zip(range(x_left, x_right), range(size_h)):
            for j, l in zip(range(y_bot, y_top), range(size_v)):
                tmp[k, l] = img[i, j]
        new_images.append(tmp)
    return new_images

In [8]:
grey_imgs = all_images.copy()
imgs_to_grayscale(grey_imgs)
new_images = cut_images(extreme_points, grey_imgs)

[[ 76   6]
 [ 73 212]
 [171 116]
 [  5 102]]
img_shape: (218, 180)
x_left: 6 --- x_right: 212 --- y_bot: 5 --- y_top: 171
[[  0   0]
 [  0 359]
 [318 359]
 [  0   0]]
img_shape: (360, 319)
x_left: 0 --- x_right: 359 --- y_bot: 0 --- y_top: 318
[[131  10]
 [163 345]
 [272 225]
 [ 17 170]]
img_shape: (348, 287)
x_left: 10 --- x_right: 345 --- y_bot: 17 --- y_top: 272
[[152  18]
 [144 322]
 [274 202]
 [ 27 164]]
img_shape: (336, 300)
x_left: 18 --- x_right: 322 --- y_bot: 27 --- y_top: 274
[[234   0]
 [274 629]
 [567 400]
 [ 35 361]]
img_shape: (630, 587)
x_left: 0 --- x_right: 629 --- y_bot: 35 --- y_top: 567
[[  2 958]
 [  0 992]
 [ 29 973]
 [  0 960]]
img_shape: (993, 825)
x_left: 958 --- x_right: 992 --- y_bot: 0 --- y_top: 29
[[  0 843]
 [ 17 872]
 [ 36 860]
 [  0 843]]
img_shape: (890, 700)
x_left: 843 --- x_right: 872 --- y_bot: 0 --- y_top: 36
[[100   5]
 [ 86 240]
 [185 145]
 [ 14 124]]
img_shape: (246, 205)
x_left: 5 --- x_right: 240 --- y_bot: 14 --- y_top: 185
[[105   4]
 [ 86